logging:
  file: gears-cip-dev.log
  level:
    org:
      springframework: INFO
    root: INFO
    
mybatis:
  type-aliases-package: com.smartwater.edm
  
server:
  port: 5000
  use-forward-headers: true
  
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://10.10.23.17:5432/gears
    username: postgres
